// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,a
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRsECvw7Qh6BbqOO5t-4kVpxVZRyJG-20',
    appId: '1:622616384606:web:d34e647af7e63e6592d0cf',
    messagingSenderId: '622616384606',
    projectId: 'emotionalgram-4dc03',
    authDomain: 'emotionalgram-4dc03.firebaseapp.com',
    storageBucket: 'emotionalgram-4dc03.appspot.com',
    measurementId: 'G-E6BX3WS3KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTtCvJFo0-rAvpR5hgQP_EnwqmjiBj3Xk',
    appId: '1:622616384606:android:87852ca5dab7071192d0cf',
    messagingSenderId: '622616384606',
    projectId: 'emotionalgram-4dc03',
    storageBucket: 'emotionalgram-4dc03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHASx07UyQs6M1M7NNS723W-xK4GrQ2V0',
    appId: '1:622616384606:ios:a83a605320766f1b92d0cf',
    messagingSenderId: '622616384606',
    projectId: 'emotionalgram-4dc03',
    storageBucket: 'emotionalgram-4dc03.appspot.com',
    iosClientId: '622616384606-71k2r1h2d6ll9ueqtsv0huag7r9nvrdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHASx07UyQs6M1M7NNS723W-xK4GrQ2V0',
    appId: '1:622616384606:ios:fbbe1956a0617e8692d0cf',
    messagingSenderId: '622616384606',
    projectId: 'emotionalgram-4dc03',
    storageBucket: 'emotionalgram-4dc03.appspot.com',
    iosClientId: '622616384606-d93bq2tiuldk00o4rd9pkbn7dfrcrn8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionGram.RunnerTests',
  );
}
